os: linux
dist: xenial
services: mongodb
language: node_js
node_js: 10
install:
    - npm install
    - npm run lint
    - npm run test
addons:
    ssh_known_hosts: vps514431.ovh.net
before_install:
  openssl aes-256-cbc -K $encrypted_d7d5642ee6fe_key -iv $encrypted_d7d5642ee6fe_iv -in deploy/deploy-key.enc -out deploy/deploy-key -d
deploy:
    - provider: script
        script: bash ./deploy/deploy-production.sh
        on:
            branch: master
    - provider: script
        script: bash ./deploy/deploy-sandbox.sh
        on:
            branch: staging
